// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogizbipvatakimxzmoaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9naXpiaXB2YXRha2lteHptb2FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NDUyNDUsImV4cCI6MjA2MDUyMTI0NX0.SvOYmnL-fJORsgnoySWUHl1eS72i00dEEG_kzcbYEL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);