
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../../types/supabase';

const SUPABASE_URL = "https://qububdncbfxslxtmujws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1YnViZG5jYmZ4c2x4dG11andzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDE5NTksImV4cCI6MjA2NjAxNzk1OX0.CmUaM3bZtQEqClmcjLdn382ZbhSmuN8tcTX7qfYRTWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
